services:
  ha:
    container_name: "home-assistant"
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - "./home-assistant:/config"
    environment:
      TZ: "Africa/Johannesburg"
    restart: "unless-stopped"
    network_mode: "host"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-mqtt
    volumes:
      - "./mosquitto:/mosquitto"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
    ports:
      - 1883:1883
      - 9001:9001
    restart: "unless-stopped"
