services:
  ha:
    container_name: "home-assistant"
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - "./home-assistant:/config"
    environment:
      TZ: "Africa/Johannesburg"
    restart: "unless-stopped"
    network_mode: "host"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-mqtt
    volumes:
      - "./mosquitto:/mosquitto"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
    ports:
      - 1883:1883
      - 9001:9001
    restart: "unless-stopped"

  voltronic-mqtt:
    image: bushrangers/ha-voltronic-mqtt
    container_name: voltronic-mqtt
    privileged: true
    restart: always
    volumes:
      - ./inverter/config/:/etc/inverter/

    devices:
      #  - "/dev/mem:/dev/mem"

      # USB Port Mapping
      - /dev/bus/usb:/dev/bus/usb:rwm
      - /dev/ttyUSB0:/dev/ttyUSB0:rwm
      - /dev/ttyUSB1:/dev/ttyUSB1:rwm

      # Serial Port Mapping...
      - /dev/ttyS0:/dev/ttyS0
      - /dev/ttyS1:/dev/ttyS1
      - /dev/ttyS2:/dev/ttyS2
